"""
50+ Indian foods with accurate macro data per 100g.
Sources: ICMR NIN food composition tables + USDA FoodData.
"""
FOODS = [
    # ── Grains ────────────────────────────────────────────────────────────────
    {'name': 'White Rice (cooked)', 'category': 'grain', 'calories_per_100g': 130, 'protein_per_100g': 2.7, 'carbs_per_100g': 28.2, 'fat_per_100g': 0.3, 'fiber_per_100g': 0.4, 'serving_size_g': 150, 'serving_label': '1 cup', 'diet_type': 'vegan', 'ingredients': ['rice'], 'tags': ['vegan', 'high_carb', 'low_fat']},
    {'name': 'Brown Rice (cooked)', 'category': 'grain', 'calories_per_100g': 123, 'protein_per_100g': 2.6, 'carbs_per_100g': 25.6, 'fat_per_100g': 0.9, 'fiber_per_100g': 1.8, 'serving_size_g': 150, 'serving_label': '1 cup', 'diet_type': 'vegan', 'ingredients': ['brown rice'], 'tags': ['vegan', 'high_carb', 'low_fat']},
    {'name': 'Whole Wheat Roti', 'category': 'grain', 'calories_per_100g': 264, 'protein_per_100g': 8.0, 'carbs_per_100g': 52.0, 'fat_per_100g': 3.5, 'fiber_per_100g': 4.6, 'serving_size_g': 40, 'serving_label': '1 roti', 'diet_type': 'veg', 'ingredients': ['whole wheat flour', 'water'], 'tags': ['veg', 'moderate_protein', 'fiber_source', 'high_carb']},
    {'name': 'Maida Roti / Naan', 'category': 'grain', 'calories_per_100g': 300, 'protein_per_100g': 9.0, 'carbs_per_100g': 58.0, 'fat_per_100g': 4.0, 'fiber_per_100g': 1.2, 'serving_size_g': 90, 'serving_label': '1 naan', 'diet_type': 'veg', 'ingredients': ['maida', 'water', 'yeast'], 'tags': ['veg', 'moderate_protein', 'high_carb', 'refined_flour']},
    {'name': 'Poha (cooked)', 'category': 'grain', 'calories_per_100g': 110, 'protein_per_100g': 2.5, 'carbs_per_100g': 22.0, 'fat_per_100g': 1.5, 'fiber_per_100g': 0.8, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['flattened rice', 'onion', 'peanuts', 'spices'], 'tags': ['vegan', 'moderate_calorie', 'low_fat', 'contains_nuts']},
    {'name': 'Upma (cooked)', 'category': 'grain', 'calories_per_100g': 105, 'protein_per_100g': 2.8, 'carbs_per_100g': 18.0, 'fat_per_100g': 2.5, 'fiber_per_100g': 1.0, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['semolina', 'onion', 'mustard seeds', 'oil'], 'tags': ['vegan', 'moderate_calorie', 'low_fat', 'cooked']},
    {'name': 'Idli (steamed)', 'category': 'grain', 'calories_per_100g': 58, 'protein_per_100g': 2.0, 'carbs_per_100g': 11.6, 'fat_per_100g': 0.4, 'fiber_per_100g': 0.5, 'serving_size_g': 60, 'serving_label': '1 idli', 'diet_type': 'vegan', 'ingredients': ['rice', 'urad dal', 'salt'], 'tags': ['vegan', 'low_calorie', 'low_fat']},
    {'name': 'Dosa (plain)', 'category': 'grain', 'calories_per_100g': 133, 'protein_per_100g': 3.9, 'carbs_per_100g': 23.0, 'fat_per_100g': 3.0, 'fiber_per_100g': 0.8, 'serving_size_g': 100, 'serving_label': '1 dosa', 'diet_type': 'vegan', 'ingredients': ['rice', 'urad dal', 'oil'], 'tags': ['vegan', 'low_fat', 'cooked']},
    {'name': 'Paratha (plain, oil)', 'category': 'grain', 'calories_per_100g': 260, 'protein_per_100g': 6.5, 'carbs_per_100g': 40.0, 'fat_per_100g': 8.5, 'fiber_per_100g': 3.5, 'serving_size_g': 80, 'serving_label': '1 paratha', 'diet_type': 'veg', 'ingredients': ['whole wheat flour', 'oil', 'salt'], 'tags': ['veg', 'fiber_source', 'high_carb', 'cooked']},
    {'name': 'Jowar Roti (Bhakri)', 'category': 'grain', 'calories_per_100g': 250, 'protein_per_100g': 8.5, 'carbs_per_100g': 48.0, 'fat_per_100g': 2.0, 'fiber_per_100g': 6.0, 'serving_size_g': 45, 'serving_label': '1 bhakri', 'diet_type': 'vegan', 'ingredients': ['jowar flour', 'water'], 'tags': ['vegan', 'moderate_protein', 'high_fiber', 'high_carb', 'low_fat']},
    {'name': 'Bajra Roti', 'category': 'grain', 'calories_per_100g': 260, 'protein_per_100g': 9.0, 'carbs_per_100g': 46.0, 'fat_per_100g': 4.0, 'fiber_per_100g': 5.0, 'serving_size_g': 45, 'serving_label': '1 roti', 'diet_type': 'vegan', 'ingredients': ['bajra flour', 'water'], 'tags': ['vegan', 'moderate_protein', 'high_fiber', 'high_carb']},
    {'name': 'Oats (cooked)', 'category': 'grain', 'calories_per_100g': 68, 'protein_per_100g': 2.4, 'carbs_per_100g': 12.0, 'fat_per_100g': 1.4, 'fiber_per_100g': 1.7, 'serving_size_g': 240, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['oats', 'water'], 'tags': ['vegan', 'moderate_calorie', 'low_fat']},

    # ── Lentils & Legumes ─────────────────────────────────────────────────────
    {'name': 'Toor Dal (cooked)', 'category': 'protein', 'calories_per_100g': 116, 'protein_per_100g': 7.0, 'carbs_per_100g': 20.0, 'fat_per_100g': 0.4, 'fiber_per_100g': 3.5, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['toor dal', 'water', 'spices'], 'tags': ['vegan', 'fiber_source', 'moderate_calorie', 'low_fat']},
    {'name': 'Moong Dal (cooked)', 'category': 'protein', 'calories_per_100g': 105, 'protein_per_100g': 7.2, 'carbs_per_100g': 18.5, 'fat_per_100g': 0.4, 'fiber_per_100g': 4.1, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['moong dal', 'water', 'spices'], 'tags': ['vegan', 'fiber_source', 'moderate_calorie', 'low_fat']},
    {'name': 'Masoor Dal (cooked)', 'category': 'protein', 'calories_per_100g': 116, 'protein_per_100g': 9.0, 'carbs_per_100g': 20.0, 'fat_per_100g': 0.4, 'fiber_per_100g': 4.0, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['masoor dal', 'water', 'spices'], 'tags': ['vegan', 'moderate_protein', 'fiber_source', 'moderate_calorie', 'low_fat']},
    {'name': 'Chana Dal (cooked)', 'category': 'protein', 'calories_per_100g': 164, 'protein_per_100g': 8.9, 'carbs_per_100g': 27.2, 'fat_per_100g': 2.7, 'fiber_per_100g': 6.8, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['chana dal', 'water', 'spices'], 'tags': ['vegan', 'moderate_protein', 'high_fiber', 'high_carb', 'low_fat']},
    {'name': 'Rajma (cooked)', 'category': 'protein', 'calories_per_100g': 127, 'protein_per_100g': 8.7, 'carbs_per_100g': 22.8, 'fat_per_100g': 0.5, 'fiber_per_100g': 6.4, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['kidney beans', 'water', 'spices'], 'tags': ['vegan', 'moderate_protein', 'high_fiber', 'low_fat']},
    {'name': 'Chole / Chickpea (cooked)', 'category': 'protein', 'calories_per_100g': 164, 'protein_per_100g': 8.9, 'carbs_per_100g': 27.4, 'fat_per_100g': 2.6, 'fiber_per_100g': 7.6, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['chickpeas', 'water', 'spices'], 'tags': ['vegan', 'moderate_protein', 'high_fiber', 'high_carb', 'low_fat']},
    {'name': 'Sprouted Moong', 'category': 'protein', 'calories_per_100g': 30, 'protein_per_100g': 3.0, 'carbs_per_100g': 5.9, 'fat_per_100g': 0.2, 'fiber_per_100g': 1.8, 'serving_size_g': 100, 'serving_label': '1 cup', 'diet_type': 'vegan', 'ingredients': ['sprouted moong'], 'tags': ['vegan', 'low_calorie', 'low_carb', 'low_fat']},

    # ── Protein (Non-veg) ─────────────────────────────────────────────────────
    {'name': 'Chicken Breast (cooked)', 'category': 'protein', 'calories_per_100g': 165, 'protein_per_100g': 31.0, 'carbs_per_100g': 0.0, 'fat_per_100g': 3.6, 'fiber_per_100g': 0.0, 'serving_size_g': 150, 'serving_label': '1 medium piece', 'diet_type': 'non_veg', 'ingredients': ['chicken breast'], 'tags': ['non_veg', 'high_protein', 'low_carb']},
    {'name': 'Egg (whole, boiled)', 'category': 'protein', 'calories_per_100g': 155, 'protein_per_100g': 13.0, 'carbs_per_100g': 1.1, 'fat_per_100g': 11.0, 'fiber_per_100g': 0.0, 'serving_size_g': 50, 'serving_label': '1 egg', 'diet_type': 'non_veg', 'ingredients': ['egg'], 'tags': ['non_veg', 'moderate_protein', 'low_carb', 'contains_egg']},
    {'name': 'Egg White (boiled)', 'category': 'protein', 'calories_per_100g': 52, 'protein_per_100g': 11.0, 'carbs_per_100g': 0.7, 'fat_per_100g': 0.2, 'fiber_per_100g': 0.0, 'serving_size_g': 33, 'serving_label': '1 egg white', 'diet_type': 'non_veg', 'ingredients': ['egg white'], 'tags': ['non_veg', 'moderate_protein', 'low_calorie', 'low_carb', 'low_fat', 'contains_egg']},
    {'name': 'Fish (Rohu, cooked)', 'category': 'protein', 'calories_per_100g': 97, 'protein_per_100g': 17.0, 'carbs_per_100g': 0.0, 'fat_per_100g': 3.0, 'fiber_per_100g': 0.0, 'serving_size_g': 150, 'serving_label': '1 piece', 'diet_type': 'non_veg', 'ingredients': ['rohu fish', 'spices'], 'tags': ['non_veg', 'high_protein', 'moderate_calorie', 'low_carb', 'low_fat']},
    {'name': 'Mutton (cooked)', 'category': 'protein', 'calories_per_100g': 263, 'protein_per_100g': 25.6, 'carbs_per_100g': 0.0, 'fat_per_100g': 17.0, 'fiber_per_100g': 0.0, 'serving_size_g': 150, 'serving_label': '1 serving', 'diet_type': 'non_veg', 'ingredients': ['mutton', 'spices'], 'tags': ['non_veg', 'high_protein', 'low_carb', 'high_fat']},
    {'name': 'Tuna (canned in water)', 'category': 'protein', 'calories_per_100g': 116, 'protein_per_100g': 26.0, 'carbs_per_100g': 0.0, 'fat_per_100g': 1.0, 'fiber_per_100g': 0.0, 'serving_size_g': 85, 'serving_label': '1/2 can', 'diet_type': 'non_veg', 'ingredients': ['tuna', 'water'], 'tags': ['non_veg', 'high_protein', 'moderate_calorie', 'low_carb', 'low_fat']},

     # ── Dairy ─────────────────────────────────────────────────────────────────
    {'name': 'Paneer (full fat)', 'category': 'dairy', 'calories_per_100g': 265, 'protein_per_100g': 18.3, 'carbs_per_100g': 3.4, 'fat_per_100g': 20.8, 'fiber_per_100g': 0.0, 'serving_size_g': 100, 'serving_label': '100g', 'diet_type': 'veg', 'ingredients': ['milk solids', 'lemon'], 'tags': ['veg', 'high_protein', 'low_carb', 'high_fat']},
    {'name': 'Paneer (low fat)', 'category': 'dairy', 'calories_per_100g': 170, 'protein_per_100g': 19.0, 'carbs_per_100g': 4.5, 'fat_per_100g': 8.0, 'fiber_per_100g': 0.0, 'serving_size_g': 100, 'serving_label': '100g', 'diet_type': 'veg', 'ingredients': ['low fat milk solids', 'lemon'], 'tags': ['veg', 'high_protein', 'low_carb']},
    {'name': 'Curd / Dahi (full fat)', 'category': 'dairy', 'calories_per_100g': 98, 'protein_per_100g': 3.5, 'carbs_per_100g': 4.7, 'fat_per_100g': 6.0, 'fiber_per_100g': 0.0, 'serving_size_g': 200, 'serving_label': '1 cup', 'diet_type': 'veg', 'ingredients': ['milk', 'culture'], 'tags': ['veg', 'moderate_calorie', 'low_carb', 'contains_dairy']},
    {'name': 'Curd / Dahi (low fat)', 'category': 'dairy', 'calories_per_100g': 56, 'protein_per_100g': 4.5, 'carbs_per_100g': 4.7, 'fat_per_100g': 0.9, 'fiber_per_100g': 0.0, 'serving_size_g': 200, 'serving_label': '1 cup', 'diet_type': 'veg', 'ingredients': ['low fat milk', 'culture'], 'tags': ['veg', 'low_calorie', 'low_carb', 'low_fat']},
    {'name': 'Milk (full fat)', 'category': 'dairy', 'calories_per_100g': 61, 'protein_per_100g': 3.2, 'carbs_per_100g': 4.8, 'fat_per_100g': 3.3, 'fiber_per_100g': 0.0, 'serving_size_g': 250, 'serving_label': '1 glass', 'diet_type': 'veg', 'ingredients': ['milk'], 'tags': ['veg', 'moderate_calorie', 'low_carb', 'contains_dairy']},
    {'name': 'Milk (toned)', 'category': 'dairy', 'calories_per_100g': 44, 'protein_per_100g': 3.3, 'carbs_per_100g': 4.8, 'fat_per_100g': 1.5, 'fiber_per_100g': 0.0, 'serving_size_g': 250, 'serving_label': '1 glass', 'diet_type': 'veg', 'ingredients': ['toned milk'], 'tags': ['veg', 'low_calorie', 'low_carb', 'low_fat']},
    {'name': 'Greek Yogurt (plain)', 'category': 'dairy', 'calories_per_100g': 59, 'protein_per_100g': 10.0, 'carbs_per_100g': 3.6, 'fat_per_100g': 0.4, 'fiber_per_100g': 0.0, 'serving_size_g': 170, 'serving_label': '1 cup', 'diet_type': 'veg', 'ingredients': ['milk', 'culture'], 'tags': ['veg', 'moderate_protein', 'low_calorie', 'low_carb', 'low_fat', 'contains_dairy']},
    {'name': 'Whey Protein (powder)', 'category': 'dairy', 'calories_per_100g': 370, 'protein_per_100g': 75.0, 'carbs_per_100g': 8.0, 'fat_per_100g': 4.0, 'fiber_per_100g': 0.0, 'serving_size_g': 30, 'serving_label': '1 scoop', 'diet_type': 'veg', 'ingredients': ['whey protein'], 'tags': ['veg', 'high_protein', 'low_carb', 'fitness_friendly']},
 
     # ── Vegetables ────────────────────────────────────────────────────────────
    {'name': 'Spinach (cooked)', 'category': 'vegetable', 'calories_per_100g': 23, 'protein_per_100g': 2.9, 'carbs_per_100g': 3.6, 'fat_per_100g': 0.4, 'fiber_per_100g': 2.4, 'serving_size_g': 100, 'serving_label': '1 cup', 'diet_type': 'vegan', 'ingredients': ['spinach'], 'tags': ['vegan', 'low_calorie', 'low_carb', 'low_fat', 'whole_food']},
    {'name': 'Broccoli (cooked)', 'category': 'vegetable', 'calories_per_100g': 35, 'protein_per_100g': 2.4, 'carbs_per_100g': 7.2, 'fat_per_100g': 0.4, 'fiber_per_100g': 3.3, 'serving_size_g': 100, 'serving_label': '1 cup', 'diet_type': 'vegan', 'ingredients': ['broccoli'], 'tags': ['vegan', 'fiber_source', 'low_calorie', 'low_carb', 'low_fat', 'whole_food']},
    {'name': 'Potato (boiled)', 'category': 'vegetable', 'calories_per_100g': 87, 'protein_per_100g': 1.9, 'carbs_per_100g': 20.0, 'fat_per_100g': 0.1, 'fiber_per_100g': 1.8, 'serving_size_g': 150, 'serving_label': '1 medium', 'diet_type': 'vegan', 'ingredients': ['potato'], 'tags': ['vegan', 'moderate_calorie', 'low_fat', 'whole_food']},
    {'name': 'Sweet Potato (boiled)', 'category': 'vegetable', 'calories_per_100g': 76, 'protein_per_100g': 1.4, 'carbs_per_100g': 17.7, 'fat_per_100g': 0.1, 'fiber_per_100g': 2.5, 'serving_size_g': 130, 'serving_label': '1 medium', 'diet_type': 'vegan', 'ingredients': ['sweet potato'], 'tags': ['vegan', 'fiber_source', 'moderate_calorie', 'low_fat', 'whole_food']},
    {'name': 'Bhindi / Okra (cooked)', 'category': 'vegetable', 'calories_per_100g': 38, 'protein_per_100g': 1.9, 'carbs_per_100g': 7.5, 'fat_per_100g': 0.2, 'fiber_per_100g': 3.2, 'serving_size_g': 100, 'serving_label': '1 cup', 'diet_type': 'vegan', 'ingredients': ['okra'], 'tags': ['vegan', 'fiber_source', 'low_calorie', 'low_carb', 'low_fat', 'whole_food']},
    {'name': 'Aloo Gobi (cooked)', 'category': 'vegetable', 'calories_per_100g': 85, 'protein_per_100g': 2.5, 'carbs_per_100g': 12.0, 'fat_per_100g': 3.0, 'fiber_per_100g': 2.5, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['potato', 'cauliflower', 'oil', 'spices'], 'tags': ['vegan', 'fiber_source', 'moderate_calorie', 'low_fat', 'cooked', 'whole_food']},
    {'name': 'Palak Paneer (cooked)', 'category': 'vegetable', 'calories_per_100g': 140, 'protein_per_100g': 7.0, 'carbs_per_100g': 8.0, 'fat_per_100g': 9.0, 'fiber_per_100g': 1.8, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'veg', 'ingredients': ['spinach', 'paneer', 'oil', 'spices'], 'tags': ['veg', 'low_carb', 'contains_dairy', 'cooked', 'whole_food']},
    {'name': 'Tomato (raw)', 'category': 'vegetable', 'calories_per_100g': 18, 'protein_per_100g': 0.9, 'carbs_per_100g': 3.9, 'fat_per_100g': 0.2, 'fiber_per_100g': 1.2, 'serving_size_g': 120, 'serving_label': '1 medium', 'diet_type': 'vegan', 'ingredients': ['tomato'], 'tags': ['vegan', 'low_calorie', 'low_carb', 'low_fat', 'whole_food']},
    {'name': 'Cucumber (raw)', 'category': 'vegetable', 'calories_per_100g': 16, 'protein_per_100g': 0.7, 'carbs_per_100g': 3.6, 'fat_per_100g': 0.1, 'fiber_per_100g': 0.5, 'serving_size_g': 120, 'serving_label': '1 medium', 'diet_type': 'vegan', 'ingredients': ['cucumber'], 'tags': ['vegan', 'low_calorie', 'low_carb', 'low_fat', 'whole_food']},
 
     # ── Fruits ────────────────────────────────────────────────────────────────
    {'name': 'Banana', 'category': 'fruit', 'calories_per_100g': 89, 'protein_per_100g': 1.1, 'carbs_per_100g': 23.0, 'fat_per_100g': 0.3, 'fiber_per_100g': 2.6, 'serving_size_g': 120, 'serving_label': '1 medium', 'diet_type': 'vegan', 'ingredients': ['banana'], 'tags': ['vegan', 'fiber_source', 'moderate_calorie', 'low_fat', 'whole_food']},
    {'name': 'Apple', 'category': 'fruit', 'calories_per_100g': 52, 'protein_per_100g': 0.3, 'carbs_per_100g': 14.0, 'fat_per_100g': 0.2, 'fiber_per_100g': 2.4, 'serving_size_g': 150, 'serving_label': '1 medium', 'diet_type': 'vegan', 'ingredients': ['apple'], 'tags': ['vegan', 'low_calorie', 'low_fat', 'whole_food']},
    {'name': 'Mango (Alphonso)', 'category': 'fruit', 'calories_per_100g': 60, 'protein_per_100g': 0.8, 'carbs_per_100g': 15.0, 'fat_per_100g': 0.4, 'fiber_per_100g': 1.6, 'serving_size_g': 200, 'serving_label': '1 medium', 'diet_type': 'vegan', 'ingredients': ['mango'], 'tags': ['vegan', 'low_calorie', 'low_fat', 'whole_food']},
    {'name': 'Papaya', 'category': 'fruit', 'calories_per_100g': 43, 'protein_per_100g': 0.5, 'carbs_per_100g': 11.0, 'fat_per_100g': 0.3, 'fiber_per_100g': 1.7, 'serving_size_g': 200, 'serving_label': '1 cup diced', 'diet_type': 'vegan', 'ingredients': ['papaya'], 'tags': ['vegan', 'low_calorie', 'low_fat', 'whole_food']},
    {'name': 'Orange', 'category': 'fruit', 'calories_per_100g': 47, 'protein_per_100g': 0.9, 'carbs_per_100g': 12.0, 'fat_per_100g': 0.1, 'fiber_per_100g': 2.4, 'serving_size_g': 130, 'serving_label': '1 medium', 'diet_type': 'vegan', 'ingredients': ['orange'], 'tags': ['vegan', 'low_calorie', 'low_fat', 'whole_food']},
 
     # ── Fats & Nuts ───────────────────────────────────────────────────────────
    {'name': 'Almonds', 'category': 'fat', 'calories_per_100g': 579, 'protein_per_100g': 21.2, 'carbs_per_100g': 21.6, 'fat_per_100g': 49.9, 'fiber_per_100g': 12.5, 'serving_size_g': 28, 'serving_label': '1 oz (~23 almonds)', 'diet_type': 'vegan', 'ingredients': ['almonds'], 'tags': ['vegan', 'high_protein', 'high_fiber', 'high_fat', 'contains_nuts']},
    {'name': 'Walnuts', 'category': 'fat', 'calories_per_100g': 654, 'protein_per_100g': 15.2, 'carbs_per_100g': 13.7, 'fat_per_100g': 65.2, 'fiber_per_100g': 6.7, 'serving_size_g': 28, 'serving_label': '1 oz (~14 halves)', 'diet_type': 'vegan', 'ingredients': ['walnuts'], 'tags': ['vegan', 'high_protein', 'high_fiber', 'high_fat', 'contains_nuts']},
    {'name': 'Peanut Butter', 'category': 'fat', 'calories_per_100g': 588, 'protein_per_100g': 25.0, 'carbs_per_100g': 20.0, 'fat_per_100g': 50.0, 'fiber_per_100g': 6.0, 'serving_size_g': 32, 'serving_label': '2 tbsp', 'diet_type': 'vegan', 'ingredients': ['peanuts', 'oil', 'salt'], 'tags': ['vegan', 'high_protein', 'high_fiber', 'high_fat', 'contains_nuts', 'cooked']},
    {'name': 'Ghee', 'category': 'fat', 'calories_per_100g': 900, 'protein_per_100g': 0.0, 'carbs_per_100g': 0.0, 'fat_per_100g': 100.0, 'fiber_per_100g': 0.0, 'serving_size_g': 5, 'serving_label': '1 tsp', 'diet_type': 'vegan', 'ingredients': ['milk fat'], 'tags': ['vegan', 'low_carb', 'high_fat']},
    {'name': 'Coconut Oil', 'category': 'fat', 'calories_per_100g': 862, 'protein_per_100g': 0.0, 'carbs_per_100g': 0.0, 'fat_per_100g': 100.0, 'fiber_per_100g': 0.0, 'serving_size_g': 14, 'serving_label': '1 tbsp', 'diet_type': 'vegan', 'ingredients': ['coconut oil'], 'tags': ['vegan', 'low_carb', 'high_fat']},
    {'name': 'Flaxseeds', 'category': 'fat', 'calories_per_100g': 534, 'protein_per_100g': 18.3, 'carbs_per_100g': 28.9, 'fat_per_100g': 42.2, 'fiber_per_100g': 27.3, 'serving_size_g': 15, 'serving_label': '1 tbsp', 'diet_type': 'vegan', 'ingredients': ['flaxseeds'], 'tags': ['vegan', 'high_protein', 'high_fiber', 'high_carb', 'high_fat']},
 
     # ── Beverages / Snacks ────────────────────────────────────────────────────
    {'name': 'Chai (milk tea, no sugar)', 'category': 'beverage', 'calories_per_100g': 26, 'protein_per_100g': 1.2, 'carbs_per_100g': 3.0, 'fat_per_100g': 1.0, 'fiber_per_100g': 0.0, 'serving_size_g': 150, 'serving_label': '1 cup', 'diet_type': 'veg', 'ingredients': ['tea', 'milk', 'water'], 'tags': ['veg', 'low_calorie', 'low_carb', 'low_fat', 'contains_dairy', 'beverage']},
    {'name': 'Coconut Water', 'category': 'beverage', 'calories_per_100g': 19, 'protein_per_100g': 0.7, 'carbs_per_100g': 3.7, 'fat_per_100g': 0.2, 'fiber_per_100g': 1.1, 'serving_size_g': 240, 'serving_label': '1 glass', 'diet_type': 'vegan', 'ingredients': ['coconut water'], 'tags': ['vegan', 'low_calorie', 'low_carb', 'low_fat', 'beverage']},
    {'name': 'Buttermilk (chaas, low fat)', 'category': 'beverage', 'calories_per_100g': 40, 'protein_per_100g': 3.3, 'carbs_per_100g': 4.8, 'fat_per_100g': 0.9, 'fiber_per_100g': 0.0, 'serving_size_g': 200, 'serving_label': '1 glass', 'diet_type': 'veg', 'ingredients': ['buttermilk', 'water', 'spices'], 'tags': ['veg', 'low_calorie', 'low_carb', 'low_fat', 'beverage']},
    {'name': 'Masala Peanuts', 'category': 'snack', 'calories_per_100g': 544, 'protein_per_100g': 23.0, 'carbs_per_100g': 30.0, 'fat_per_100g': 38.0, 'fiber_per_100g': 7.0, 'serving_size_g': 30, 'serving_label': 'small handful', 'diet_type': 'veg', 'ingredients': ['peanuts', 'spices', 'oil'], 'tags': ['veg', 'high_protein', 'high_fiber', 'high_carb', 'high_fat', 'contains_nuts', 'cooked', 'snack']},
    {'name': 'Murukku', 'category': 'snack', 'calories_per_100g': 490, 'protein_per_100g': 8.0, 'carbs_per_100g': 65.0, 'fat_per_100g': 22.0, 'fiber_per_100g': 2.5, 'serving_size_g': 50, 'serving_label': '4-5 pieces', 'diet_type': 'veg', 'ingredients': ['rice flour', 'urad dal flour', 'oil', 'spices'], 'tags': ['veg', 'moderate_protein', 'fiber_source', 'high_carb', 'high_fat', 'cooked', 'snack', 'fried']},
    {'name': 'Samosa (fried)', 'category': 'snack', 'calories_per_100g': 262, 'protein_per_100g': 4.5, 'carbs_per_100g': 32.0, 'fat_per_100g': 13.0, 'fiber_per_100g': 2.0, 'serving_size_g': 100, 'serving_label': '1 samosa', 'diet_type': 'veg', 'ingredients': ['maida', 'potato', 'oil', 'spices'], 'tags': ['veg', 'high_carb', 'refined_flour', 'cooked', 'snack', 'fried']},
    {'name': 'Protein Bar (generic)', 'category': 'snack', 'calories_per_100g': 380, 'protein_per_100g': 30.0, 'carbs_per_100g': 35.0, 'fat_per_100g': 10.0, 'fiber_per_100g': 5.0, 'serving_size_g': 60, 'serving_label': '1 bar', 'diet_type': 'veg', 'ingredients': ['protein blend', 'oats', 'nuts', 'sweetener'], 'tags': ['veg', 'high_protein', 'high_fiber', 'high_carb', 'snack', 'fitness_friendly']},

     # ── Popular Indian Meals ──────────────────────────────────────────────────
    {'name': 'Chicken Biryani', 'category': 'protein', 'calories_per_100g': 195, 'protein_per_100g': 11.0, 'carbs_per_100g': 24.0, 'fat_per_100g': 6.0, 'fiber_per_100g': 1.2, 'serving_size_g': 350, 'serving_label': '1 plate', 'diet_type': 'non_veg', 'ingredients': ['rice', 'chicken', 'oil', 'spices'], 'tags': ['non_veg', 'moderate_protein', 'cooked']},
    {'name': 'Paneer Butter Masala', 'category': 'protein', 'calories_per_100g': 180, 'protein_per_100g': 8.0, 'carbs_per_100g': 10.0, 'fat_per_100g': 13.0, 'fiber_per_100g': 1.5, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'veg', 'ingredients': ['paneer', 'butter', 'tomato', 'cream', 'spices'], 'tags': ['veg', 'moderate_protein', 'low_carb', 'contains_dairy', 'cooked']},
    {'name': 'Dal Makhani', 'category': 'protein', 'calories_per_100g': 140, 'protein_per_100g': 7.5, 'carbs_per_100g': 16.0, 'fat_per_100g': 5.5, 'fiber_per_100g': 4.0, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'veg', 'ingredients': ['whole urad dal', 'rajma', 'butter', 'cream', 'spices'], 'tags': ['veg', 'fiber_source', 'contains_dairy', 'cooked']},
    {'name': 'Rajma Chawal', 'category': 'protein', 'calories_per_100g': 145, 'protein_per_100g': 6.5, 'carbs_per_100g': 25.0, 'fat_per_100g': 2.5, 'fiber_per_100g': 4.5, 'serving_size_g': 350, 'serving_label': '1 plate', 'diet_type': 'vegan', 'ingredients': ['kidney beans', 'rice', 'spices'], 'tags': ['vegan', 'fiber_source', 'high_carb', 'low_fat']},
    {'name': 'Pav Bhaji', 'category': 'grain', 'calories_per_100g': 190, 'protein_per_100g': 5.0, 'carbs_per_100g': 28.0, 'fat_per_100g': 7.0, 'fiber_per_100g': 3.0, 'serving_size_g': 300, 'serving_label': '2 pav + bhaji', 'diet_type': 'veg', 'ingredients': ['pav', 'mixed vegetables', 'butter', 'spices'], 'tags': ['veg', 'fiber_source', 'high_carb', 'contains_dairy', 'cooked']},
    {'name': 'Chole Bhature', 'category': 'grain', 'calories_per_100g': 250, 'protein_per_100g': 7.0, 'carbs_per_100g': 32.0, 'fat_per_100g': 11.0, 'fiber_per_100g': 4.0, 'serving_size_g': 300, 'serving_label': '1 bhatura + chole', 'diet_type': 'vegan', 'ingredients': ['chickpeas', 'maida', 'oil', 'spices'], 'tags': ['vegan', 'fiber_source', 'high_carb', 'refined_flour', 'cooked', 'fried']},
    {'name': 'Masala Dosa', 'category': 'grain', 'calories_per_100g': 175, 'protein_per_100g': 4.5, 'carbs_per_100g': 26.0, 'fat_per_100g': 6.0, 'fiber_per_100g': 2.0, 'serving_size_g': 200, 'serving_label': '1 dosa', 'diet_type': 'vegan', 'ingredients': ['rice', 'urad dal', 'potato', 'oil', 'spices'], 'tags': ['vegan', 'high_carb', 'cooked']},
    {'name': 'Vegetable Pulao', 'category': 'grain', 'calories_per_100g': 150, 'protein_per_100g': 3.5, 'carbs_per_100g': 28.0, 'fat_per_100g': 3.0, 'fiber_per_100g': 2.0, 'serving_size_g': 250, 'serving_label': '1 plate', 'diet_type': 'vegan', 'ingredients': ['rice', 'mixed vegetables', 'oil', 'spices'], 'tags': ['vegan', 'high_carb', 'low_fat', 'cooked']},
    {'name': 'Aloo Paratha (with butter)', 'category': 'grain', 'calories_per_100g': 280, 'protein_per_100g': 6.5, 'carbs_per_100g': 38.0, 'fat_per_100g': 11.0, 'fiber_per_100g': 3.0, 'serving_size_g': 120, 'serving_label': '1 paratha', 'diet_type': 'veg', 'ingredients': ['whole wheat flour', 'potato', 'butter', 'oil', 'spices'], 'tags': ['veg', 'fiber_source', 'high_carb', 'contains_dairy', 'cooked']},
    {'name': 'Egg Bhurji', 'category': 'protein', 'calories_per_100g': 180, 'protein_per_100g': 12.0, 'carbs_per_100g': 4.0, 'fat_per_100g': 13.0, 'fiber_per_100g': 0.5, 'serving_size_g': 150, 'serving_label': '2 eggs cooked', 'diet_type': 'non_veg', 'ingredients': ['egg', 'onion', 'tomato', 'oil', 'spices'], 'tags': ['non_veg', 'moderate_protein', 'low_carb', 'contains_egg', 'cooked']},
    {'name': 'Chicken Curry', 'category': 'protein', 'calories_per_100g': 165, 'protein_per_100g': 15.0, 'carbs_per_100g': 6.0, 'fat_per_100g': 9.0, 'fiber_per_100g': 1.0, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'non_veg', 'ingredients': ['chicken', 'onion', 'tomato', 'oil', 'spices'], 'tags': ['non_veg', 'high_protein', 'low_carb', 'cooked']},
    {'name': 'Fish Curry (Bengali style)', 'category': 'protein', 'calories_per_100g': 130, 'protein_per_100g': 14.0, 'carbs_per_100g': 5.0, 'fat_per_100g': 6.5, 'fiber_per_100g': 0.8, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'non_veg', 'ingredients': ['fish', 'mustard oil', 'tomato', 'spices'], 'tags': ['non_veg', 'moderate_protein', 'low_carb']},
    {'name': 'Tandoori Chicken', 'category': 'protein', 'calories_per_100g': 150, 'protein_per_100g': 23.0, 'carbs_per_100g': 3.0, 'fat_per_100g': 5.5, 'fiber_per_100g': 0.5, 'serving_size_g': 200, 'serving_label': '2 pieces', 'diet_type': 'non_veg', 'ingredients': ['chicken', 'curd', 'spices'], 'tags': ['non_veg', 'high_protein', 'low_carb', 'contains_dairy']},
    {'name': 'Shahi Paneer', 'category': 'protein', 'calories_per_100g': 220, 'protein_per_100g': 9.0, 'carbs_per_100g': 9.0, 'fat_per_100g': 17.0, 'fiber_per_100g': 1.0, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'veg', 'ingredients': ['paneer', 'cream', 'butter', 'tomato', 'spices'], 'tags': ['veg', 'moderate_protein', 'low_carb', 'high_fat', 'contains_dairy', 'cooked']},
    {'name': 'Mix Veg Sabzi', 'category': 'vegetable', 'calories_per_100g': 80, 'protein_per_100g': 2.5, 'carbs_per_100g': 10.0, 'fat_per_100g': 3.5, 'fiber_per_100g': 3.0, 'serving_size_g': 150, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['mixed vegetables', 'oil', 'spices'], 'tags': ['vegan', 'fiber_source', 'moderate_calorie', 'low_carb', 'cooked', 'whole_food']},
    {'name': 'Sambar', 'category': 'protein', 'calories_per_100g': 45, 'protein_per_100g': 2.8, 'carbs_per_100g': 7.5, 'fat_per_100g': 0.8, 'fiber_per_100g': 2.5, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['toor dal', 'vegetables', 'tamarind', 'spices'], 'tags': ['vegan', 'fiber_source', 'low_calorie', 'low_carb', 'low_fat']},
    {'name': 'Rasam', 'category': 'protein', 'calories_per_100g': 25, 'protein_per_100g': 1.0, 'carbs_per_100g': 4.5, 'fat_per_100g': 0.3, 'fiber_per_100g': 0.5, 'serving_size_g': 200, 'serving_label': '1 bowl', 'diet_type': 'vegan', 'ingredients': ['tomato', 'tamarind', 'spices'], 'tags': ['vegan', 'low_calorie', 'low_carb', 'low_fat']},
 
     # ── Street Food & Fast Food ───────────────────────────────────────────────
    {'name': 'Vada Pav', 'category': 'snack', 'calories_per_100g': 230, 'protein_per_100g': 5.0, 'carbs_per_100g': 33.0, 'fat_per_100g': 9.0, 'fiber_per_100g': 2.0, 'serving_size_g': 150, 'serving_label': '1 piece', 'diet_type': 'veg', 'ingredients': ['potato', 'pav', 'oil', 'spices'], 'tags': ['veg', 'high_carb', 'cooked', 'snack', 'fried']},
    {'name': 'Pani Puri (6 pcs)', 'category': 'snack', 'calories_per_100g': 150, 'protein_per_100g': 3.5, 'carbs_per_100g': 26.0, 'fat_per_100g': 4.0, 'fiber_per_100g': 2.0, 'serving_size_g': 100, 'serving_label': '6 puris', 'diet_type': 'vegan', 'ingredients': ['semolina puri', 'potato', 'chickpeas', 'tamarind water'], 'tags': ['vegan', 'high_carb', 'snack']},
    {'name': 'Bhel Puri', 'category': 'snack', 'calories_per_100g': 165, 'protein_per_100g': 4.0, 'carbs_per_100g': 28.0, 'fat_per_100g': 4.5, 'fiber_per_100g': 2.5, 'serving_size_g': 150, 'serving_label': '1 serving', 'diet_type': 'vegan', 'ingredients': ['puffed rice', 'sev', 'onion', 'tomato', 'tamarind chutney'], 'tags': ['vegan', 'fiber_source', 'high_carb', 'snack']},
    {'name': 'Burger (veg)', 'category': 'snack', 'calories_per_100g': 245, 'protein_per_100g': 6.5, 'carbs_per_100g': 34.0, 'fat_per_100g': 9.5, 'fiber_per_100g': 2.5, 'serving_size_g': 150, 'serving_label': '1 burger', 'diet_type': 'veg', 'ingredients': ['bun', 'veg patty', 'sauce'], 'tags': ['veg', 'fiber_source', 'high_carb', 'snack']},
    {'name': 'Burger (chicken)', 'category': 'protein', 'calories_per_100g': 265, 'protein_per_100g': 14.0, 'carbs_per_100g': 28.0, 'fat_per_100g': 11.0, 'fiber_per_100g': 1.5, 'serving_size_g': 170, 'serving_label': '1 burger', 'diet_type': 'non_veg', 'ingredients': ['bun', 'chicken patty', 'sauce'], 'tags': ['non_veg', 'moderate_protein', 'high_carb']},
    {'name': 'Pizza (cheese, 1 slice)', 'category': 'snack', 'calories_per_100g': 266, 'protein_per_100g': 11.0, 'carbs_per_100g': 33.0, 'fat_per_100g': 10.0, 'fiber_per_100g': 2.0, 'serving_size_g': 100, 'serving_label': '1 slice', 'diet_type': 'veg', 'ingredients': ['maida', 'cheese', 'tomato sauce'], 'tags': ['veg', 'moderate_protein', 'high_carb', 'contains_dairy', 'refined_flour', 'snack']},
    {'name': 'French Fries', 'category': 'snack', 'calories_per_100g': 312, 'protein_per_100g': 3.4, 'carbs_per_100g': 41.0, 'fat_per_100g': 15.0, 'fiber_per_100g': 3.5, 'serving_size_g': 100, 'serving_label': 'medium portion', 'diet_type': 'vegan', 'ingredients': ['potato', 'oil', 'salt'], 'tags': ['vegan', 'fiber_source', 'high_carb', 'high_fat', 'cooked', 'snack', 'fried']},
    {'name': 'Dhokla', 'category': 'snack', 'calories_per_100g': 160, 'protein_per_100g': 5.0, 'carbs_per_100g': 28.0, 'fat_per_100g': 3.5, 'fiber_per_100g': 1.5, 'serving_size_g': 100, 'serving_label': '2 pieces', 'diet_type': 'vegan', 'ingredients': ['besan', 'curd', 'spices'], 'tags': ['vegan', 'high_carb', 'contains_dairy', 'snack']},
 
     # ── Breakfast Items ───────────────────────────────────────────────────────
    {'name': 'Bread (white, 1 slice)', 'category': 'grain', 'calories_per_100g': 265, 'protein_per_100g': 9.0, 'carbs_per_100g': 49.0, 'fat_per_100g': 3.2, 'fiber_per_100g': 2.7, 'serving_size_g': 30, 'serving_label': '1 slice', 'diet_type': 'veg', 'ingredients': ['maida', 'yeast'], 'tags': ['veg', 'moderate_protein', 'fiber_source', 'high_carb', 'refined_flour']},
    {'name': 'Bread (whole wheat, 1 slice)', 'category': 'grain', 'calories_per_100g': 247, 'protein_per_100g': 13.0, 'carbs_per_100g': 41.0, 'fat_per_100g': 4.2, 'fiber_per_100g': 7.0, 'serving_size_g': 30, 'serving_label': '1 slice', 'diet_type': 'veg', 'ingredients': ['whole wheat flour', 'yeast'], 'tags': ['veg', 'moderate_protein', 'high_fiber', 'high_carb']},
    {'name': 'Boiled Egg', 'category': 'protein', 'calories_per_100g': 155, 'protein_per_100g': 13.0, 'carbs_per_100g': 1.1, 'fat_per_100g': 11.0, 'fiber_per_100g': 0.0, 'serving_size_g': 50, 'serving_label': '1 egg', 'diet_type': 'non_veg', 'ingredients': ['egg'], 'tags': ['non_veg', 'moderate_protein', 'low_carb', 'contains_egg']},
    {'name': 'Omelette (2 eggs)', 'category': 'protein', 'calories_per_100g': 185, 'protein_per_100g': 13.5, 'carbs_per_100g': 1.5, 'fat_per_100g': 14.5, 'fiber_per_100g': 0.0, 'serving_size_g': 100, 'serving_label': '2 eggs', 'diet_type': 'non_veg', 'ingredients': ['egg', 'oil', 'salt'], 'tags': ['non_veg', 'moderate_protein', 'low_carb', 'contains_egg', 'cooked']},
    {'name': 'Cornflakes with milk', 'category': 'grain', 'calories_per_100g': 100, 'protein_per_100g': 3.5, 'carbs_per_100g': 19.0, 'fat_per_100g': 1.5, 'fiber_per_100g': 0.5, 'serving_size_g': 250, 'serving_label': '1 bowl', 'diet_type': 'veg', 'ingredients': ['cornflakes', 'milk'], 'tags': ['veg', 'moderate_calorie', 'low_fat', 'contains_dairy']},
 
     # ── Fruits ────────────────────────────────────────────────────────────────
    {'name': 'Banana Shake', 'category': 'beverage', 'calories_per_100g': 90, 'protein_per_100g': 3.0, 'carbs_per_100g': 16.0, 'fat_per_100g': 2.0, 'fiber_per_100g': 0.5, 'serving_size_g': 300, 'serving_label': '1 glass', 'diet_type': 'veg', 'ingredients': ['banana', 'milk'], 'tags': ['veg', 'moderate_calorie', 'low_fat', 'contains_dairy', 'beverage']},
    {'name': 'Mango Lassi', 'category': 'beverage', 'calories_per_100g': 85, 'protein_per_100g': 3.0, 'carbs_per_100g': 14.0, 'fat_per_100g': 2.0, 'fiber_per_100g': 0.3, 'serving_size_g': 300, 'serving_label': '1 glass', 'diet_type': 'veg', 'ingredients': ['mango', 'curd', 'milk'], 'tags': ['veg', 'moderate_calorie', 'low_fat', 'contains_dairy', 'beverage']},
    {'name': 'Protein Shake (whey + milk)', 'category': 'beverage', 'calories_per_100g': 70, 'protein_per_100g': 8.0, 'carbs_per_100g': 7.0, 'fat_per_100g': 1.5, 'fiber_per_100g': 0.0, 'serving_size_g': 300, 'serving_label': '1 shake', 'diet_type': 'veg', 'ingredients': ['whey protein', 'milk'], 'tags': ['veg', 'moderate_protein', 'moderate_calorie', 'low_carb', 'low_fat', 'contains_dairy', 'beverage', 'fitness_friendly']},
 
     # ── Sweets & Desserts ─────────────────────────────────────────────────────
    {'name': 'Gulab Jamun', 'category': 'snack', 'calories_per_100g': 385, 'protein_per_100g': 5.5, 'carbs_per_100g': 56.0, 'fat_per_100g': 15.0, 'fiber_per_100g': 0.5, 'serving_size_g': 60, 'serving_label': '1 piece', 'diet_type': 'veg', 'ingredients': ['khoya', 'sugar syrup', 'flour'], 'tags': ['veg', 'high_carb', 'high_fat', 'snack']},
    {'name': 'Rasgulla', 'category': 'snack', 'calories_per_100g': 186, 'protein_per_100g': 4.5, 'carbs_per_100g': 38.0, 'fat_per_100g': 1.5, 'fiber_per_100g': 0.0, 'serving_size_g': 60, 'serving_label': '1 piece', 'diet_type': 'veg', 'ingredients': ['chena', 'sugar syrup'], 'tags': ['veg', 'high_carb', 'low_fat', 'snack']},
    {'name': 'Kheer (rice pudding)', 'category': 'snack', 'calories_per_100g': 156, 'protein_per_100g': 4.0, 'carbs_per_100g': 26.0, 'fat_per_100g': 4.5, 'fiber_per_100g': 0.2, 'serving_size_g': 150, 'serving_label': '1 bowl', 'diet_type': 'veg', 'ingredients': ['rice', 'milk', 'sugar'], 'tags': ['veg', 'high_carb', 'contains_dairy', 'snack']},
    {'name': 'Halwa (sooji)', 'category': 'snack', 'calories_per_100g': 310, 'protein_per_100g': 4.5, 'carbs_per_100g': 44.0, 'fat_per_100g': 13.0, 'fiber_per_100g': 1.0, 'serving_size_g': 100, 'serving_label': '1 serving', 'diet_type': 'veg', 'ingredients': ['semolina', 'ghee', 'sugar'], 'tags': ['veg', 'high_carb', 'contains_dairy', 'cooked', 'snack']},
    {'name': 'Dark Chocolate (70%)', 'category': 'snack', 'calories_per_100g': 598, 'protein_per_100g': 7.8, 'carbs_per_100g': 45.0, 'fat_per_100g': 42.0, 'fiber_per_100g': 10.9, 'serving_size_g': 30, 'serving_label': '3 squares', 'diet_type': 'veg', 'ingredients': ['cocoa', 'cocoa butter', 'sugar'], 'tags': ['veg', 'high_fiber', 'high_carb', 'high_fat', 'snack']},
]
